### ISSUE TITLE
Upload and download with progress?

### ISSUE THREAD

**Issue by KeyMetricSoft** [DecaTec/Portable-WebDAV-Library#10]
Hello,

The release history mentions that it's possible to upload/download with progress, but that functionality is supported only for the UWP library variant.

Are there plans to support this on the .NET library side?

Regards,

Mark R.

**Comment by DecaTec** [comment]
Let me investigate if this can be implemented in the NetFx part, too.

**Comment by DecaTec** [comment]
The best solution would be using the [ProgressMessageHandler](https://msdn.microsoft.com/en-us/library/system.net.http.handlers.progressmessagehandler(v=vs.118).aspx) from the ASP.NET Web API Client: https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/
You can use this message handler to create an instance of WebDavClient/WebDavSession. This should provide you with progress information.

**Comment by DecaTec** [comment]
Here's the workflow: 

* Right click on your project in Visual Studio 
* _Manage NuGet Packages..._

![unbenannt](https://cloud.githubusercontent.com/assets/9428899/20933749/4e853042-bbd9-11e6-89ad-f1f4fdd786eb.png)

* Then add _Microsoft.AspNet.WebApi.Client_ NuGet package to your solution:

![unbenannt2](https://cloud.githubusercontent.com/assets/9428899/20933829/846bf024-bbd9-11e6-97bb-f6afa611b997.png)

Thereafter, you can chain the ProgressMessageHandler with a HttpClientHandler in order to get progress information:

```csharp
private async void button1_Click(object sender, EventArgs e)
{
    var credentials = new NetworkCredential("UserName", "MyPassword");
    HttpClientHandler httpMessageHandler = new HttpClientHandler() { Credentials = credentials };
    ProgressMessageHandler progressMessageHandler = new ProgressMessageHandler();
    progressMessageHandler.HttpReceiveProgress += ProgressMessageHandler_HttpReceiveProgress;
    progressMessageHandler.InnerHandler = httpMessageHandler;

    var webDavSession = new WebDavSession(@"http://www.myserver.com/webdav/", progressMessageHandler);

    using (Stream s = new FileStream(@"C:\temp\file.img", FileMode.OpenOrCreate))
    {
        var result = await webDavSession.DownloadFileAsync(@"file.img", s);
    }
}

private void ProgressMessageHandler_HttpReceiveProgress(object sender, HttpProgressEventArgs e)
{
    // Handle the download progress here.
    var transferred = e.BytesTransferred;
    var percentage = e.ProgressPercentage;
    // ...
}
```

**Comment by KeyMetricSoft** [comment]
Thanks very much for taking the time to outline the workflow in this manner. Very helpful indeed, and I'll give it a try within the next few days.

Do you ultimately envision progress support being added directly to the library (e.g. in a future version)?

**Comment by DecaTec** [comment]
> Do you ultimately envision progress support being added directly to the library (e.g. in a future version)?

No, I don't thinks so, sorry.
I cloud try to mimic the behavior of an ASP.NET ProgressHandler, but why writing code which already exists? I think this should be Microsoft's task to pull these things into .NET (Core), just because this is a question asked 1000 times on the internet.

But I think this is a good workaround: Only one additional DLL has to be shipped with your project and there are no side effects.

**Comment by KeyMetricSoft** [comment]
No need to apologize, I think your perspective on this is well-reasoned.

Thanks again for your assistance, and for the high quality of your library.

**Comment by DecaTec** [comment]
I've added a wiki entry about tracking upload/download progress with the NetFx part of the library (maybe useful for others searching for a similar solution): https://github.com/DecaTec/Portable-WebDAV-Library/wiki/Download-Upload-with-progress-using-the-Portable-WebDAV-Library-(NetFx)

**Comment by DecaTec** [comment]
The upcoming version 0.7.0.0 will target .NETStandard 1.1 (so, .NET Framework 4.5 or later) and there is no separation between NetFx/UWP anymore.
The library is used in some UWP projects relying on upload/download with progress. As the workaround shown above won't work on UWP, I had to find another way to support upload/download with progress directly in the library.
So v0.7.0.0 will support upload/download with progress (even on .NET Framework applications). This version will be released shortly.
