### ISSUE TITLE
Set Translate header to f to force IIS WebDAV to serve unmapped files

### ISSUE THREAD

**Issue by devatwork** [DecaTec/Portable-WebDAV-Library#36]
I just found out why WinSCP is able to download files from IIS with custom extensions as opposed to other clients, including this one.

It turns out it sends an `Translate: f` header, which forces IIS to serve the file as is even if it's extension is not mapped.

See https://winscp.net/tracker/show_bug.cgi?id=1255 for the original WinSCP issue and the Ms documentation here: https://msdn.microsoft.com/en-us/library/cc250063.aspx

The rfc4918 does not state mention the header but WinSCP sends it along for every GET request. I will run some more tests to see if it does so consistently. If so, I'll send a PR to address this.

**Comment by DecaTec** [comment]
I was not aware of this problem, but I just installed an IIS test environment (especially for lock testing; Nextcloud/ownCloud doesn't support WebDAV locking).
I'll also have a look at it.

**Comment by DecaTec** [comment]
I was able to reproduce this "error".
This branch seems to resolve the issue: https://github.com/DecaTec/Portable-WebDAV-Library/tree/translate-header-iis

Some things which came to my mind:
- Should be always set the Translate header to 'f', or should there be a property? 
- This lib should be as generic as possible and this would be the first workaround (especially for IIS) introduced in the lib...
- Could this be a security issue for IIS? Even if the file extension is know, the server will always serve a 'raw' representation. This could lead to unwanted side effects. Just think about an ASP file which is not interpreted and the server simply returns the source code.
- Is this a client issue or a server configuration issue?

**Comment by DecaTec** [comment]
Should be resolved with https://github.com/DecaTec/Portable-WebDAV-Library/commit/d3b35f262e0e419302f60c0ff97b51dd65f54768

I thought about not setting this header as DefaultRequestHeader, but only on a `GET`. 
I stumbled upon the same behavior on `HEAD`, so I decided to leave it as default header.

Should do no harm (assumed that the IIS is configured properly).

I prepare for v0.8.0.0 - and skip v0.7.1.0 as there are quite a lot of changes since v0.7.0.0.
