### ISSUE TITLE
Properties that are not in RFC4918

### ISSUE THREAD

**Issue by TomGroeneboer** [DecaTec/Portable-WebDAV-Library#40]
The [Prop.cs](https://github.com/DecaTec/Portable-WebDAV-Library/blob/master/DecaTec.WebDav/WebDavArtifacts/Prop.cs) class does define properties that are not in [RFC-4918](https://tools.ietf.org/html/rfc4918). 

This class should be RFC4918 compliant, right? If there is need for extensions to this spec, could you please split the extensions from the base RFC implementation?

Properties that are not in RFC4918:
- [Source](https://github.com/DecaTec/Portable-WebDAV-Library/blob/master/DecaTec.WebDav/WebDavArtifacts/Prop.cs#L239)
- [ContentClass](https://github.com/DecaTec/Portable-WebDAV-Library/blob/master/DecaTec.WebDav/WebDavArtifacts/Prop.cs#L259)
- [DefaultDocument](https://github.com/DecaTec/Portable-WebDAV-Library/blob/master/DecaTec.WebDav/WebDavArtifacts/Prop.cs#L269)
- [IsHidden](https://github.com/DecaTec/Portable-WebDAV-Library/blob/master/DecaTec.WebDav/WebDavArtifacts/Prop.cs#L299)
- [IsReadOnly](https://github.com/DecaTec/Portable-WebDAV-Library/blob/master/DecaTec.WebDav/WebDavArtifacts/Prop.cs#L309)
- [IsRoot](https://github.com/DecaTec/Portable-WebDAV-Library/blob/master/DecaTec.WebDav/WebDavArtifacts/Prop.cs#L319)
- [IsStructuredDocument](https://github.com/DecaTec/Portable-WebDAV-Library/blob/master/DecaTec.WebDav/WebDavArtifacts/Prop.cs#L329)
- [LastAccessed](https://github.com/DecaTec/Portable-WebDAV-Library/blob/master/DecaTec.WebDav/WebDavArtifacts/Prop.cs#L339)
- [Name](https://github.com/DecaTec/Portable-WebDAV-Library/blob/master/DecaTec.WebDav/WebDavArtifacts/Prop.cs#L349)
- [ParentName](https://github.com/DecaTec/Portable-WebDAV-Library/blob/master/DecaTec.WebDav/WebDavArtifacts/Prop.cs#L359)

**Comment by DecaTec** [comment]
These properties are mostly there for IIS compatibility. Removing these properties will lead to some stange behavior, e.g. in `WebDavSession.List`.
Is there any special need in removing these properties?

However, I should think about being able to support cusom properties here (defined by the client), e.g. for ownCloud. They're also defining custom properties.

**Comment by TomGroeneboer** [comment]
These properties are misleading. I saw the `IsHidden` property and wanted to see if any CMS returned their system folders with this property, but they did not. Then I went on a search on the ins and outs of this property and found out that it is not a default WebDAV property. 

In my opinion, the `Prop` class should only expose the default RFC props and there should be some kind of extension mechanism to define custom properties.

**Comment by DecaTec** [comment]
In general, you're right.

I've tried to implement a more general approach where the client could specify a class derived from `Prop` containing additional properties (e.g. for ownCloud/Nextcloud). If you want have a look at it, it's on a separate branch: https://github.com/DecaTec/Portable-WebDAV-Library/tree/prop-generic
All classes working with `Prop` needs to be generic then. I faced some runtime exceptions with this approach. Also, it would make the use of the library a little more difficult, because even `WebDavClient` and `WebDavSession` needs to be generic then.

However, there are some properties which are not part of RFC 4918, but of [RFC 4331](https://tools.ietf.org/html/rfc4331). Additionally there were some properties from [Additional WebDAV Collection Properties](https://tools.ietf.org/html/draft-hopmann-collection-props-00). Some, but not all...

I've kept with the current approach, putting it all in one class `Prop`: https://github.com/DecaTec/Portable-WebDAV-Library/commit/a9ec94a667f4ab5e9b533ceae43decedb5a0a150

For clarification, I've also updated the documentation stating that properties containing default values (false, 0, etc.) maybe are on default values because the WebDAV server simply doesn't support these properties.

**Comment by DecaTec** [comment]
`WebDavSessionListItem` now has (strongly typed) nullable properties.
Before this change, it was not obvious for most properties if the server doesn't support these properties (default values for the data types were used) or if the properties were supported but false, 0, etc.

**Comment by DecaTec** [comment]
I've tried to make `WebDavSession` and `WebDavClient` more generic (inject the types which are used as `Prop`). Unfortunately, I wasn't able to get it running in a user friendly way.

For now, I'll say that it's up to the client to expand the WebDAV object model by overriding methods of `WebDavSession` and/or `WebDavClient`.
To be able to derive from `WebDavSession`/`WebDavClient`, I exposed some of the important methods and properties as `protected`.

I'm involved in another project where the requirement is to support more Props beside the default Props implemented in the library. I'll have a look if we can integrate the new Props in the WebDAV object model.

However, with all the changes made, I've decided to release v0.9.0.0.

If you have any other idea in making the lib more generic, please let me know. I'll leave the corresponding branch as it is, although it's definitely out of date.
