### ISSUE TITLE
Uploaded files have the upload time as last change date instead of the one of the uploaded file.

### ISSUE THREAD

**Issue by kevinboss** [DecaTec/Portable-WebDAV-Library#44]
Maybe this is expected behavior and I can do this in some other way.

Issue:
1. Create local file with last change date 6:15 AM
2. Upload said file at 6:30 AM

Expected: File on server has as last change date: 6:15 AM
Actual result: File on server has as last change date: 6:30 AM

**Comment by DecaTec** [comment]
I think that all the date values (lat accessed, creation date, etc.) are managed by the server and should not be altered by the client.
[RFC 4918](http://www.webdav.org/specs/rfc4918.html#PROPERTY_getlastmodified) say that
> The last-modified date on a resource SHOULD only reflect changes in the body (the GET responses) of the resource.

So, when the file was uploaded at 6:30 AM, the last change of the body actually was on 6:30 AM. So I think this behavior is expected.

**Comment by kevinboss** [comment]
That just says that altering a property should not alter the last-change-date. Only changes to the actual file should change the last-change-date.

I guess PROPPATCH should be sufficient to patch the create and change-dates.

How do I need to do that? This is my code so far, but I only get "BadRequest" as response:

```
var pu = new PropertyUpdate
            {
                Items = new object[]
                {
                    new Prop
                    {
                        GetLastModified = DateTime.Today.ToString(CultureInfo.CurrentCulture)
                    }
                }
            };

using (var client = new WebDavClient(new HttpClientHandler
            {
                Credentials = GetCredentials()
            }))
            {
                var result = await client.PropPatchAsync(remoteFilePath, pu);
            }
```

**Comment by DecaTec** [comment]
You are missing a `Set` in for the `PropertyUpdate`:

````cs
var pu = new PropertyUpdate();
var set = new Set();

var prop = new Prop()
{
	GetLastModified = DateTime.Today.ToString(CultureInfo.CurrentCulture)
};

set.Prop = prop;
pu.Items = new object[] { set };

using (var client = new WebDavClient(new HttpClientHandler
{
	Credentials = GetCredentials()
}))
{
	var result = await client.PropPatchAsync(remoteFilePath, pu);
}
````

But the server may handle this property as protected (according to RFC 4918):

> Protected: SHOULD be protected because some clients may rely on the value for appropriate caching behavior, or on the value of the Last-Modified header to which this property is linked.

So, when a client tries to change the last modified date, the server may return an error.

What WebDAV server you are using?

**Comment by kevinboss** [comment]
> What WebDAV server you are using?

IIS

I could also write to a different property, like "lastModified" but then I couldn't use the WebDavSession and WebDavSessionItem classes since they look at the "getLastModified" property.

**Comment by DecaTec** [comment]
When there's a need to use other properties as defined in `Prop` (this is where the `WebDavSessionListItem` gets its data), you could use classes derived from `WebDavSession` (when using v0.9.0.0 of the lib). But then, there have to be derived classes/substitutes for everything down to `Prop`: `WebDavSession`, `WebDavSessionListItem`, `WebDavClient`,  `WebDavResponseContentParser`, `MultiStatus`, `Prop`, `Propfind`, `Propstat`, `Response`, etc. You see, pretty much to do...

The intention of `WebDavSession` was an easy access to WebDAV (_as long as you're only using properties defined in [RFC 4918](http://tools.ietf.org/html/rfc4918), [RFC 4331](https://tools.ietf.org/html/rfc4331), [Additional WebDAV Collection Properties](https://tools.ietf.org/html/draft-hopmann-collection-props-00) and a some IIS WebDAV properties_). For any "special purposes", you'll have to use the "low level" `WebDavClient`.

But that being said, by simply implementing an own property (like "lastModified"), the server will not know about this property and it's pretty much useless because it will only get "ignored" by the server.

**Comment by kevinboss** [comment]
I see...well then I guess I am stuck.

My scenario is as follow:

1. Client one edits a file (local)
2. Client two edits the same file (local)
3. Client one uploads said file (and the last-change-date will be the upload date)
4. Client two (even though he edited the file at a later date) has now an older last-change-date for his local file and will download the file from the server instead of uploading the local file to the server

But if that is how it is then I will just leave it like that. I am currently working on a project where I had to write a library that keeps a local and a WebDav (it is possible that multiple clients target the same WebDav folder) folder in sync. I wanted to open-source the sync-library part of the project. But before I can do that I really need to figure out how to solve the scenario above.

But thanks anyway so far 👍

**Comment by DecaTec** [comment]
Maybe a bit off topic, but...

Personally I wouldn't go for any date values for detrmination which file version is the "correct" one.
In your use case (and assuming that the last modified date would be set by the server correctly), cilent two will upload his file in step 4 and will override the file submitted by client one (step 3). In most cases, this is not intended.

When implementing a sync mechanism you have to look at the ETag: Before a client uploads a file, he has to compare the current ETag of the file (server side) to the ETag when the file was last downloaded (therefore, this ETag needs to be saved somewhere on the client side). When ETag (server) != ETag (client), then the file was changed from another source (e.g. another client). In this case you'll have to ask the user which file version is the correct one (the one to keep) or offer some kind of merge mechanism.
Otherwise you'll always end up in some (not intended) override issues.
