### ISSUE TITLE
Problem with char '#' in dest url (movesync)

### ISSUE THREAD

**Issue by milkin-vl** [DecaTec/Portable-WebDAV-Library#58]
I found that char '#' in dest url (for movesync) not escaped and this fail operation.

Other WebDav clients (for example Cyberduck) encode '#' to %23

**Comment by DecaTec** [comment]
Resolved with f450b90087e707d2a938d1b6b3b7c6bba434b6c6
Nuget package released, should be available soon.

The problem was  that the number sign ('#') is a special character in a URL (fragment - part of a resource). Usually this shouldn't be taken into account when it comes to resources specified in a URL, but for WebDAV it makes sense that this a also a valid character for folders.

Edit: This was even a bigger problem because not only copy/move failed, but als any other operation with a URL containing '#' (e.g. MKCOL). But should be solved right now.

**Comment by milkin-vl** [comment]
Yes, now it works :+1:  Many thanks for your job!
