### ISSUE TITLE
Exception thrown: 'DecaTec.WebDav.Exceptions.WebDavException' in mscorlib.dll 

### ISSUE THREAD

**Issue by valkaben** [DecaTec/Portable-WebDAV-Library#63]
I have a WebDAV server running on apache2 on Ubuntu 16.04 LTS.  One of my users is getting the following error when attempting to list files in the WebDAV from his application:

     Exception thrown: 'DecaTec.WebDav.Exceptions.WebDavException' in mscorlib.dll
     Error while executing ListAsync (wrong response status code). Expected status code: 207 (MultiStatus); actual status code: 401 (Unauthorized)

I'm not sure if this is a server issue or a client issue.  My user is able to get into the WebDAV directory with his app but as soon as he tries to list anything, he gets the mentioned error.  If it is a server side error, what do I need to change?

**Comment by valkaben** [comment]
user informed me that he needed trailing '/' added to his path lines to avoid this error when connecting to my server.

**Comment by DecaTec** [comment]
So it only works with a trailing slash at the end of the URL?
That's strange, because the error you're receiving from the server is a HTTP 401 then. That means 'unauthorized' and should only occur when wrong user credentials are given. This is a strange behavior of the server.
Have you found any entries in the server's log regarding this issue?
